exports.music_name_fixtures = [
	{ name: `a tribe called quest`, _id: `a tribe called quest` },
	{ name: `ahmad jamal`, _id: `ahmad jamal` },
	{ name: `allan holdsworth`, _id: `allan holdsworth` },
	{ name: `amália rodrigues`, _id: `amália rodrigues` },
	{ name: `andres schiff`, _id: `andres schiff` },
	{ name: `andromeda mega express orchestra`, _id: `andromeda mega express orchestra` },
	{ name: `antje weithaas`, _id: `antje weithaas` },
	{ name: `anton webern`, _id: `anton webern` },
	{ name: `arthur rubinstein` , _id: `arthur rubinstein`  },
	{ name: `beauty boys`, _id: `beauty boys` },
	{ name: `billie holiday`, _id: `billie holiday` },
	{ name: `brian blade`, _id: `brian blade` },
	{ name: `byrd`, _id: `byrd` },
	{ name: `béla bartók`, _id: `béla bartók` },
	{ name: `can sco lafaro`, _id: `can sco lafaro` },
	{ name: `cannibal corpse`, _id: `cannibal corpse` },
	{ name: `claude debussy`, _id: `claude debussy` },
	{ name: `cream`, _id: `cream` },
	{ name: `damon albarn`, _id: `damon albarn` },
	{ name: `daniil shafran`, _id: `daniil shafran` },
	{ name: `das schwäbische jugendsinfonieorchester`, _id: `das schwäbische jugendsinfonieorchester` },
	{ name: `dead kennedys`, _id: `dead kennedys` },
	{ name: `denise beck`, _id: `denise beck` },
	{ name: `dhruba ghosh`, _id: `dhruba ghosh` },
	{ name: `die fantastischen vier`, _id: `die fantastischen vier` },
	{ name: `dmitri shostakovich`, _id: `dmitri shostakovich` },
	{ name: `domenico scarlatti`, _id: `domenico scarlatti` },
	{ name: `duke ellington`, _id: `duke ellington` },
	{ name: `earth, wind & fire`, _id: `earth, wind & fire` },
	{ name: `edgar varèse`, _id: `edgar varèse` },
	{ name: `eric dolphy`, _id: `eric dolphy` },
	{ name: `errol garner`, _id: `errol garner` },
	{ name: `flying lotus`, _id: `flying lotus` },
	{ name: `genesis`, _id: `genesis` },
	{ name: `gerard grisey`, _id: `gerard grisey` },
	{ name: `gine e neveu`, _id: `gine e neveu` },
	{ name: `grizzly bear`, _id: `grizzly bear` },
	{ name: `györgy ligeti`, _id: `györgy ligeti` },
	{ name: `gérard grisey`, _id: `gérard grisey` },
	{ name: `harry partch` , _id: `harry partch`  },
	{ name: `hermeto pascoal`, _id: `hermeto pascoal` },
	{ name: `igor stravinsky`, _id: `igor stravinsky` },
	{ name: `j dilla`, _id: `j dilla` },
	{ name: `jackson and his computer band`, _id: `jackson and his computer band` },
	{ name: `jacques brel` , _id: `jacques brel`  },
	{ name: `james herfiel`, _id: `james herfiel` },
	{ name: `jerry goodman`, _id: `jerry goodman` },
	{ name: `jethro tull`, _id: `jethro tull` },
	{ name: `jimi hendrix`, _id: `jimi hendrix` },
	{ name: `johann haydn`, _id: `johann haydn` },
	{ name: `johann sebastian bach`, _id: `johann sebastian bach` },
	{ name: `johannes brahms`, _id: `johannes brahms` },
	{ name: `johannes schleiermacher`, _id: `johannes schleiermacher` },
	{ name: `john cage`, _id: `john cage` },
	{ name: `john coltrane`, _id: `john coltrane` },
	{ name: `john scofield`, _id: `john scofield` },
	{ name: `jordi savall` , _id: `jordi savall`  },
	{ name: `jörg widmann` , _id: `jörg widmann`  },
	{ name: `karsten nagel`, _id: `karsten nagel` },
	{ name: `king crimson`, _id: `king crimson` },
	{ name: `kurt weill`, _id: `kurt weill` },
	{ name: `lemmy`, _id: `lemmy` },
	{ name: `les claypool`, _id: `les claypool` },
	{ name: `luciano berio`, _id: `luciano berio` },
	{ name: `ludwig van beethoven`, _id: `ludwig van beethoven` },
	{ name: `martin hendl`, _id: `martin hendl` },
	{ name: `metallica`, _id: `metallica` },
	{ name: `michael jackson`, _id: `michael jackson` },
	{ name: `miles davis`, _id: `miles davis` },
	{ name: `morton feldman`, _id: `morton feldman` },
	{ name: `mr. bungle`, _id: `mr. bungle` },
	{ name: `natalia gutman`, _id: `natalia gutman` },
	{ name: `pablo casals`, _id: `pablo casals` },
	{ name: `paul hindemith`, _id: `paul hindemith` },
	{ name: `paul motian`, _id: `paul motian` },
	{ name: `pavarotti`, _id: `pavarotti` },
	{ name: `pearl jam`, _id: `pearl jam` },
	{ name: `peter brötzmann`, _id: `peter brötzmann` },
	{ name: `pharao sanders`, _id: `pharao sanders` },
	{ name: `pierre boulez`, _id: `pierre boulez` },
	{ name: `prince`, _id: `prince` },
	{ name: `queen`, _id: `queen` },
	{ name: `radu lupe`, _id: `radu lupe` },
	{ name: `rage against the machine`, _id: `rage against the machine` },
	{ name: `red hot chili peppers`, _id: `red hot chili peppers` },
	{ name: `richard clayderman`, _id: `richard clayderman` },
	{ name: `richard strauss`, _id: `richard strauss` },
	{ name: `robert schumann`, _id: `robert schumann` },
	{ name: `rush`, _id: `rush` },
	{ name: `safran ensemble`, _id: `safran ensemble` },
	{ name: `slonovski bal`, _id: `slonovski bal`  },
	{ name: `soeur marie keyrouz`, _id: `soeur marie keyrouz` },
	{ name: `steve harris`, _id: `steve harris` },
	{ name: `sufjan stevens`, _id: `sufjan stevens` },
	{ name: `pyotr ilyich tchaikovsky`, _id: `tchaikovsky` },
	{ name: `the beach boys`, _id: `the beach boys` },
	{ name: `the beatles`, _id: `the beatles` },
	{ name: `the meters`, _id: `the meters` },
	{ name: `the notwist`, _id: `the notwist` },
	{ name: `the shaggs`, _id: `the shaggs` },
	{ name: `thelonious monk`, _id: `thelonious monk` },
	{ name: `tic tac toe` , _id: `tic tac toe`  },
	{ name: `tim mindchin`, _id: `tim mindchin` },
	{ name: `tom waits`, _id: `tom waits` },
	{ name: `triole guru`, _id: `triole guru` },
	{ name: `weather report`, _id: `weather report` },
	{ name: `whitefield brothers`, _id: `whitefield brothers` }
];











